name: Update Cat Image

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  push:
    branches:
      - main

jobs:
  updateCatImage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14
        check-latest: true
      # Set the environment variable to enable ESM mode
        env:
          NODE_OPTIONS: '--experimental-specifier-resolution=node'

    - name: Install dependencies
      run: |
        npm install
        npm install node-fetch

    - name: Fetch new cat image
      run: node updateCatImage.js

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m 'Update cat image'
        git push
